routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

Route::group(['middleware' => 'auth:web'], function () {
    Route::get('/', 'IndexController@index');

    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/dashboard/async/getDateRanges', 'HomeController@asyncGetDateRanges');
    Route::post('/dashboard/async/getTiles', 'HomeController@asyncGetTiles');
    Route::post('/dashboard/async/getCharts', 'HomeController@asyncGetCharts');
    Route::post('/dashboard/async/getLists', 'HomeController@asyncGetLists');
    Route::post('/dashboard/export', 'HomeController@export');

    Route::get('/review', 'ReviewController@index');
    Route::post('/review/export', 'ReviewController@export');
    Route::post('/review/change', 'ReviewController@change');
    Route::get('/review/reply/create/{reviewId}', 'ReviewController@create')->where('reviewId', '[0-9]+');
    Route::post('/review/reply/store', 'ReviewController@store');
    Route::get('/review/reply/edit/{reviewId}', 'ReviewController@edit')->where('reviewId', '[0-9]+');
    Route::post('/review/reply/update', 'ReviewController@update');
    Route::post('/review/reply/delete', 'ReviewController@delete');
    Route::post('/review/async/findIsAutoreplied', 'ReviewController@asyncFindIsAutoreplied');
    Route::post('/review/async/findLocations', 'ReviewController@asyncFindLocations');
    Route::post('/review/async/updateAutoReplied', 'ReviewController@asyncUpdateAutoReplied');
    Route::post('/review/async/getAutoReplied', 'ReviewController@asyncGetAutoReplied');
    
    Route::get('/template', 'ReviewReplyTemplateController@index');
    Route::get('/template/create', 'ReviewReplyTemplateController@create');
    Route::post('/template/store', 'ReviewReplyTemplateController@store');
    Route::get('/template/{reviewReplyTemplateId}', 'ReviewReplyTemplateController@edit')->where('reviewReplyTemplateId', '[0-9]+');
    Route::post('/template/update', 'ReviewReplyTemplateController@update');
    Route::post('/template/delete', 'ReviewReplyTemplateController@delete');
    Route::post('/template/async/find', 'ReviewReplyTemplateController@asyncFind');

    Route::get('/localpost', 'LocalPostGroupController@index');
    Route::get('/localpost/create', 'LocalPostGroupController@create');
    Route::post('/localpost/store', 'LocalPostGroupController@store');
    Route::get('/localpost/edit/{localPostGroupId}', 'LocalPostGroupController@edit');
    Route::post('/localpost/update', 'LocalPostGroupController@update');
    Route::post('/localpost/export', 'LocalPostGroupController@export');
    Route::post('/localpost/upload', 'LocalPostGroupController@upload');
    Route::delete('/localpost/destroy/{localPostGroupId}', 'LocalPostGroupController@destroy');

    Route::get('/location', 'LocationController@index');
    Route::get('/location/create', 'LocationController@create');
    Route::post('/location/store', 'LocationController@store');
    Route::get('/location/edit/{locationId}', 'LocationController@edit');
    Route::post('/location/update', 'LocationController@update');
    Route::delete('/location/destroy/{locationId}', 'LocationController@destroy');

    Route::get('/photo', 'PhotoController@index');
    Route::get('/photo/create', 'PhotoController@create');
    Route::get('/photo/edit/{mediaItem2GroupId}', 'PhotoController@edit');
    Route::post('/photo/store', 'PhotoController@store');
    Route::post('/photo/update', 'PhotoController@update');
    Route::post('/photo/delete', 'PhotoController@delete');

    Route::get('/contact', 'ContactController@index');

    Route::get('/photo/create', 'PhotoController@create');

    // ユーザー管理
    Route::get('/user/register', 'UserController@showRegistrationForm')->name('user.register');
    Route::resource('user', 'UserController')->except(['create' ]);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    const CREATED_AT = 'create_time';
    const UPDATED_AT = 'update_time';

    protected $primaryKey = 'user_id';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role_id',
        'enterprise_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public function enterprise()
    {
        return $this->belongsTo('App\Enterprise', 'enterprise_id', 'enterprise_id');
    }

    public function roles()
    {
        return $this->hasMany(Role::class, 'role_id', 'role_id');
    }

    public function isAdmin()
    {
        // return $this->roles()->where('role_id', Role::ADMIN_ROLE_ID)->exists();
        // システム全体の管理権限なので、users.id = 1 に固定する。
        return ($this->user_id == 1);
    }

    /**
     * ログインユーザーが所属している企業の「契約タイプ」を取得する。
     * 通常は session を使用し、取得できなければDBから参照。
     *
     * @return integer
     */
    public function getContractType() : ?int
    {
        $contract_type = session(config('formConst.SESSION_CONTRACT_TYPE')) ?? $this->enterprise->contract_type;
        return $contract_type;
    }

    public function setContractType($contract_type) : void
    {
        session([config('formConst.SESSION_CONTRACT_TYPE') => $contract_type]);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Account;
use App\Enterprise;
use App\Http\Requests\User\UserRequest;
use App\Services\UserService;
use App\User;
use App\UserRole;
use Exception;
use Illuminate\Auth\Events\Registered;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{

    // ユーザー登録を行うため trait を利用する
    use RegistersUsers;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, UserService $service)
    {
        Gate::authorize('admin');

        $users = $service->search($request)->paginate(config('formConst.PAGINATE_MAX_LIMIT'));
        $enterprises = $service->getEnterprises()->all();
        return view('user/index', compact('users', 'enterprises'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function showRegistrationForm()
    {
        Gate::authorize('admin');

        $variables = [
            'user' => new User(),
            'isCreate' => true,
            'isReadOnly' => false,
            'enterprises' => Enterprise::all(),
            'accounts' => Account::all(),
            'user_roles' => null
        ];
        return view('user/create', $variables);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request, UserService $service)
    {
        try {
            DB::beginTransaction();
            $new_user = $this->create($request->all());
            event(new Registered($new_user));
            $service->saveUserRoles($request, $new_user);
            DB::commit();
            return redirect(route('user.index'))->with('success', 'ユーザーを登録しました');
        } catch (Exception $e) {
            DB::rollBack();
            logger()->error($e);
            return back()->withErrors('ユーザーの登録時にエラーが発生しました')->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user, UserService $service)
    {
        Gate::authorize('admin');

        $params = [
            'user' => $user,
            'isCreate' => false,
            'isReadOnly' => false,
            'enterprises' => Enterprise::all(),
            'accounts' => Account::all(),
            'user_roles' => UserRole::getUserRole($user->user_id)->get(),
            'access_control' => config('const.ACCESS_CONTROL')[UserRole::getUserRole($user->user_id)->first()->role_id ?? 0]
        ];
        // 新規登録・更新を同じ blade で行っているため create を呼び出す
        return view('user/create', $params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user, UserService $service)
    {
        try {
            DB::beginTransaction();
            $user = $this->create($request->all());
            $service->saveUserRoles($request, $user);
            event(new Registered($user));
            DB::commit();
            return redirect(route('user.index'))->with('success', 'ユーザーを更新しました');
        } catch (Exception $e) {
            DB::rollBack();
            logger()->error($e);
            return back()->withErrors('ユーザーの更新時にエラーが発生しました')->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, UserService $service)
    {
        try {
            $service->destroy($request);
            return redirect(action('UserController@index'))->with('success', 'ユーザーを削除しました');
        } catch (Exception $e) {
            logger()->error($e->getMessage());
            return back()->withErrors('ユーザーの削除時にエラーが発生しました')->withInput();
        }
    }

    // php artisan make:auth で生成される RegisterController.php からオーバーライド用にコピー＋修正した。
    // ▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼▼
    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data): User
    {
        $current_user = Auth::user();
        // role_id の値は固定。所属企業がParaWorksさんかどうか？で判定する。
        $users_role_id
            = ($data['enterprise_id'] == config('formConst.PARAWORKS_ENTERPRISE_ID')) ? 1 : 0;
        $values = [
            'name' => $data['users_name'],
            'email' => $data['users_email'],
            'role_id' => $users_role_id,
            'enterprise_id' => $data['enterprise_id'],
        ];
        // 新規登録、編集でpassword指定があった場合
        if ($data['users_password']) {
            $values['password'] = bcrypt($data['users_password']);
        }

        return User::updateOrCreate(
            [
                'user_id' => $data['user_id']
            ],
            $values
        );
    }
    // ▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲▲

}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('title', 'ユーザー編集')

@section('head')
<link href="{{ mix('css/user.css') }}" rel="stylesheet">
<script>
    TOPIC_TYPE = JSON.parse('{!! json_encode(config("formConst.GMB_TOPIC_TYPE")) !!}');
</script>
<script type="text/javascript" src="{{ mix('js/user_create.js') }}" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js"></script>
<script>
    const isCreate = {{ $isCreate ?'true': 'false' }};
    const isReadOnly = {{ $isReadOnly ?'true': 'false' }};
</script>
@endsection

@section('content')
<div class="col-md-8 order-md-1">
    <h4 class="mb-4">ユーザー{{ $isCreate ? '作成' : '編集' }}</h4>
    <form action="{{ $isCreate ? route('user.store') : route('user.update', $user->user_id) }}" method="post"
        enctype="multipart/form-data">
        @csrf
        @if(!$isCreate)
        @method('PATCH')
        @endif
        <input type='hidden' name='user_id' value="{{$user->user_id}}" />
        <div class='container'>
            {{-- ユーザー名 --}}
            <div class='row p-2' id='name_row'>
                <div class="col-md-4 text-right">
                    <label for="users_name" class="d-block font-weight-bold">ユーザー名</label>
                </div>
                <div class='col-md-8 pr-1'>
                    {{Form::text('users_name', old('users_name', $user->name), [
                                    'id' => 'users_name',
                                    'class' => ['form-control',($errors->has('users_name')) ? 'is-invalid':''],
                                    'readonly' => $isReadOnly
                                ])}}
                    @if ($errors->has('users_name'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('users_name') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
            {{-- email --}}
            <div class='row p-2' id='email_row'>
                <div class="col-md-4 text-right">
                    <label for="users_email" class="d-block font-weight-bold">emailアドレス</label>
                </div>
                <div class='col-md-8 pr-1'>
                    {{Form::text('users_email', old('users_email', $user->email), [
                                    'id' => 'users_email',
                                    'class' => ['form-control',($errors->has('users_email')) ? 'is-invalid':''],
                                    'readonly' => $isReadOnly
                                ])}}
                    @if ($errors->has('users_email'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('users_email') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
            {{-- Password --}}
            @if(!$isCreate)
            <div class='row pt-4 pb-0'>
                <div class="col-md-4 text-right">
                </div>
                <div class='col-md-8 pr-1'>
                    <strong>※パスワードを変更する場合のみ入力してください</strong>
                </div>
            </div>
            @endif
            <div class='row p-2' id='password_row'>
                <div class="col-md-4 text-right">
                    <label for="users_password" class="d-block font-weight-bold">パスワード</label>
                </div>
                <div class='col-md-8 pr-1'>
                    {{Form::password('users_password', [
                                    'id' => 'users_password',
                                    'class' => ['form-control',($errors->has('users_password')) ? 'is-invalid':''],
                                    'readonly' => $isReadOnly
                                ])}}
                    @if ($errors->has('users_password'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('users_password') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
            {{-- Password（確認用） --}}
            <div class='row p-2' id='password_cnf_row'>
                <div class="col-md-4 text-right">
                    <label for="users_password_confirmation" class="d-block font-weight-bold">パスワード（確認用）</label>
                </div>
                <div class='col-md-8 pr-1'>
                    {{Form::password('users_password_confirmation', [
                                    'id' => 'users_password_confirmation',
                                    'class' => ['form-control',($errors->has('users_password_confirmation')) ? 'is-invalid':''],
                                    'readonly' => $isReadOnly
                                ])}}
                    @if ($errors->has('users_password_confirmation'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('users_password_confirmation') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
            {{-- 所属企業 --}}
            <div class='row py-2'>
                <div class='col-md-4 text-right'>
                    <label for="" class="d-block font-weight-bold">所属企業</label>
                </div>
                <div class='col-8'>
                    <select name="enterprise_id" id='enterprise_id'
                        class="form-control {{ $isReadOnly ? 'form-control-disabled disabled-wrapper' : '' }} {{ $errors->has('enterprise_id') ? 'is-invalid':'' }}">
                        <option value='' disabled {{ old('enterprise_id',  $user->enterprise_id) ? '' : 'selected' }}
                            data-locations="">
                            所属企業を選択してください
                        </option>
                        @forelse($enterprises as $enterprise)
                        <option value="{{ $enterprise->enterprise_id }}"
                            data-accounts="{{ optional($accounts->where('enterprise_id', '=', $enterprise->enterprise_id))->    implode('account_id', ',') }}"
                            {{ $enterprise->enterprise_id == old('enterprise_id', $user->enterprise_id) ? 'selected' : '' }}>
                            {{ $enterprise->name }}
                        </option>
                        @empty
                        <option>参照できる所属企業がありません</option>
                        @endforelse
                    </select>
                    @if ($errors->has('enterprise_id'))
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $errors->first('enterprise_id') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
            <div class='row py-2'>
                <div class='col-4 text-right'>
                    <label for="account" class="d-block font-weight-bold">ブランド</label>
                    <div>
                        <button type='button' id='btn-select-all' class='btn btn-primary p-1 m-1'>全選択
                        </button>
                    </div>
                    <div>
                        <button type='button' id='btn-de-select-all' class='btn btn-secondary p-1 m-1'>全解除
                        </button>
                    </div>
                </div>
                <div class='col-8'>
                    <div
                        class="account-checkboxes-wrapper form-control {{ $errors->has('location_id') ? 'is-invalid':'' }} {{ $isReadOnly? 'disabled-wrapper' : '' }}">
                        @forelse($accounts as $account)
                        <div class='location-row'>
                            {{Form::checkbox(
                                            'account_ids[]',
                                            $account->account_id,
                                            collect( old('account_ids[]', optional($user_roles)->pluck('account_id')) )->contains($account->account_id) ,
                                            ['id' => 'ac_' . $account->account_id, 'class' => ['location-checkboxes', $isReadOnly ? 'form-control-disabled' : '']]
                                        )}}
                            <label for="lo_{{$account->account_id}}"
                                class="{{ $isReadOnly ? 'form-control-disabled' : '' }}">{{ $account->gmb_account_name }}</label>
                        </div>
                        @empty
                        <span>参照できるブランドがありません</span>
                        @endforelse
                    </div>
                </div>
            </div>
            <div class="row py-2">
                <div class="col-md-4 text-right">
                    <label for="access_control" class="d-block font-weight-bold">アクセス制御設定</label>
                </div>
                <div class="col-md-8">
                    <div class="row text-center">
                        <div class="col-4">
                            <label for=""></label>
                        </div>
                        <div class="col-2">
                            <label for="allow">表示</label>
                        </div>
                        <div class="col-2">
                            <label for="edit">編集</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4 flexbox">
                            <label for="local_post">投稿管理<br>写真管理</label>
                        </div>
                        <div class="col-2">
                            {{Form::checkbox(
                                'allow_local_post', config('const.FLG_ON'),
                                old('allow_local_post', $isCreate ? config('const.FLG_ON') : ($access_control['allow_localpost'] ? config('const.FLG_ON') : '')),
                                ['id' => 'allow_local_post', 'class' => ['mb-3', $isReadOnly ? 'form-control-disabled' : 'form-control']]
                            )}}
                        </div>
                        <div class="col-2">
                            {{Form::checkbox(
                                'edit_local_post', config('const.FLG_ON'),
                                old('edit_local_post', $isCreate ? config('const.FLG_ON') : ($access_control['edit_localpost'] ? config('const.FLG_ON') : '')),
                                ['id' => 'edit_local_post', 'class' => ['mb-3', $isReadOnly ? 'form-control-disabled' : 'form-control']]
                            )}}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4 flexbox">
                            <label for="allow_review">クチコミ管理</label>
                        </div>
                        <div class="col-2">
                            {{Form::checkbox(
                                'allow_review', config('const.FLG_ON'),
                                old('allow_review', $isCreate ? config('const.FLG_ON') : ($access_control['allow_review'] ? config('const.FLG_ON') : '')),
                                ['id' => 'allow_review', 'class' => ['mb-3', $isReadOnly ? 'form-control-disabled' : 'form-control']]
                            )}}
                        </div>
                        <div class="col-2">
                            {{Form::checkbox(
                                'edit_review', config('const.FLG_ON'),
                                old('edit_review', $isCreate ? config('const.FLG_ON') : ($access_control['edit_review'] ? config('const.FLG_ON') : '')),
                                ['id' => 'edit_review', 'class' => ['mb-3', $isReadOnly ? 'form-control-disabled' : 'form-control']]
                            )}}
                        </div>
                    </div>
                </div>
            </div>
            {{-- 追加／更新ボタン類 --}}
            <div class="d-flex justify-content-between mb-4">
                <div class='m-3'>
                    <a href="{{route('user.index')}}">
                        <button class="btn btn-primary" type="button">一覧に戻る</button>
                    </a>
                </div>
                {{-- 「下書き」以外は修正不可 --}}
                @if(!$isReadOnly)
                <div class='m-3 d-flex'>
                    <button id="btn-submit" class="btn btn-primary" type="submit">保存
                    </button>
                </div>
                @endif
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title', 'ユーザー一覧')
@section('head')
<link href="{{mix('css/user.css')}}" rel="stylesheet">
<script type="text/javascript" src="{{mix('js/user_index.js')}}" defer></script>
@endsection
@section('content')
<h3>ユーザー一覧</h3>
<div class="row">
    <div class="col-12">
        <div class="row m-3">
            <a href="{{route('user.register')}}">
                <button class="btn btn-primary btn-block">ユーザーの作成</button>
            </a>
        </div>
    </div>
</div>
<form action="{{action('UserController@index')}}" method="get" name="template">
    <div class="row m-3">
        <div class="col-4">
            <label for="accounts">所属企業</label>
            {{Form::select('enterprise', $enterprises, request()->input('enterprise'), ['class' => 'mb-3 form-control', 'placeholder' => '選択してください'])}}
        </div>
        <div class="col-4">
        </div>
    </div>
    <div class="row justify-content-end">
        <div class="col-3 m-3">
            <button class="btn btn-success btn-block" type="submit">検索</button>
        </div>
    </div>
</form>
<form action="#" method="post" name="destroy_user_form">
    @csrf
    @method('DELETE')
    <input type="hidden" name="destroy_user_id" value="" />
</form>
<div class="row m-3">
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th class="col-id">ID</th>
                    <th class="col-name">ユーザー名</th>
                    <th class="col-name">email</th>
                    <th class="col-name">所属企業名</th>
                    <th class="col-button"></th>
                </tr>
            </thead>
            <tbody>
                @forelse($users as $user)
                <tr>
                    <td class="col-id">
                        <a href="{{action('UserController@edit', ['user' => $user->user_id])}}">{{$user->user_id}}</a>
                    </td>
                    <td class="col-name">{{$user->name}}</td>
                    <td class="col-email">{{$user->email}}</td>
                    <td class="col-name">{{$user->enterprise->name}}</td>
                    <td class="col-button">
                        <a href="{{action('UserController@edit', ['user' => $user->user_id])}}">
                            <button class="btn btn-primary">編集</button>
                        </a>
                        <button class="btn btn-danger" onClick="destroyUser({{$user->user_id}})">削除</button>
                    </td>
                </tr>
                @empty
                @endforelse
            </tbody>
        </table>
        <div class="col-md-4 mx-auto">
            {{$users->appends(request()->input())->links()}}
            <span>
                @if(is_null($users->firstItem())) 0 @else {{$users->firstItem()}} @endif ～
                @if(is_null($users->lastItem())) 0 @else {{$users->lastItem()}} @endif 件&nbsp;/&nbsp;全
                {{$users->total()}} 件
            </span>
        </div>
    </div>
</div>
<div class="row m-3">
    <div class="col-12">
        <div class="row justify-content-end float-right">
            <a href="{{route('user.register')}}">
                <button class="btn btn-primary btn-block">ユーザーの作成</button>
            </a>
        </div>
    </div>
</div>
@endsection